# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeUcjQILjYUlTIBfQwPvn0eSQ6BaDwvL
"""

import csv
import matplotlib.pyplot as plt


def load_data(filename):
    sizes = []
    selection = []
    shaker = []
    quick = []
    std = []

    with open(filename, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            sizes.append(int(row['size']))
            selection.append(float(row['selection']))
            shaker.append(float(row['shaker']))
            quick.append(float(row['quick']))
            std.append(float(row['std']))

    return sizes, selection, shaker, quick, std


def plot_all(sizes, selection, shaker, quick, std):
    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(sizes, selection, marker='o', label='Выбором')
    ax.plot(sizes, shaker,    marker='o', label='Шейкер')
    ax.plot(sizes, quick,     marker='o', label='Быстрая')
    ax.plot(sizes, std,       marker='o', label='std::sort')

    ax.set_title('Сравнение алгоритмов сортировки (все)')
    ax.set_xlabel('Размер массива (N)')
    ax.set_ylabel('Время (мс)')
    ax.legend()
    ax.grid(True)

    plt.tight_layout()
    plt.savefig('plot_all.png', dpi=150)
    plt.close()
    print('Сохранено: plot_all.png')


def plot_fast(sizes, quick, std):
    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(sizes, quick, marker='o', label='Быстрая')
    ax.plot(sizes, std,   marker='o', label='std::sort')

    ax.set_title('Сравнение быстрых алгоритмов сортировки')
    ax.set_xlabel('Размер массива (N)')
    ax.set_ylabel('Время (мс)')
    ax.legend()
    ax.grid(True)

    plt.tight_layout()
    plt.savefig('plot_fast.png', dpi=150)
    plt.close()
    print('Сохранено: plot_fast.png')


def main():
    filename = 'results.csv'
    sizes, selection, shaker, quick, std = load_data(filename)

    plot_all(sizes, selection, shaker, quick, std)
    plot_fast(sizes, quick, std)


if __name__ == '__main__':
    main()